### ISSUE TITLE
error when running demo

### ISSUE THREAD

**Issue by Da5hes** [softScheck/scff#1]
Hi there
first of all - great project! kudos
i am trying to run the demo but i encountered an error with Boto
scff seems to not pass the current groupID when trying to create an instance:

```
AWS/Boto ERROR
An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value () for parameter groupId is invalid. The value cannot be empty
 File "/usr/local/bin/scff-create-instances", line 4, in <module>
    __import__('pkg_resources').run_script('scff==0.42', 'scff-create-instances')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/scff-0.42-py3.6.egg/EGG-INFO/scripts/scff-create-instances", line 163, in <module>
NameError: name 'instance' is not defined
```

**Comment by softScheck** [comment]
Hi,
for the demo to work you either need a AWS security group "Open Port 8000" or remove it in line 40 in the scff-demo script. For all features to work SSH and port 8000 must be open. Probably should mention this in the readme.
Have a nice day

**Comment by Da5hes** [comment]
thanks for the fast response, i actually figured that out few minutes later
i opened an another issue #2  that I've encountered after setting up everything
